name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-client:
  
    runs-on: self-hosted
  
    strategy:
      matrix:
        node-version: [18.x]
  
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: client/package-lock.json

      - name: Install dependencies
        working-directory: ./client
        run: npm i

      - name: Create .env file
        working-directory: ./client
        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
        run: echo "VITE_API_BASE_URL=${VITE_API_BASE_URL}" > .env

      - name: Build the client project (if present)
        working-directory: ./client
        run: npm run build --if-present

  build-server:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: server/package-lock.json

      - name: Install dependencies
        working-directory: ./server
        run: npm i

      - name: Create .env file
        working-directory: ./server
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          PG_HOST: ${{ secrets.PG_HOST }}
          PG_PORT: ${{ secrets.PG_PORT }}
          PG_USER: ${{ secrets.PG_USER }}
          PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
          PG_DATABASE: ${{ secrets.PG_DATABASE }}
          PORT: ${{ secrets.PORT }}
        run: |
          echo "JWT_SECRET=${JWT_SECRET}" > .env
          echo "PG_HOST=${PG_HOST}" >> .env
          echo "PG_PORT=${PG_PORT}" >> .env
          echo "PG_USER=${PG_USER}" >> .env
          echo "PG_PASSWORD=${PG_PASSWORD}" >> .env
          echo "PG_DATABASE=${PG_DATABASE}" >> .env
          echo "PORT=${PORT}" >> .env
